# Configurations
title: OntoBot
longtitle: OntoBot – Human–Building conversation in natural language
author: Suhas Devmane
email: devmanesp1@cardiff.ac.uk
description: >
  OntoBot is an end-to-end platform for human–building conversation in natural language, combining Rasa, analytics microservices, and knowledge stores (SQL/SPARQL).

version: 1.0
gitbook_version: 3.2.3

url: 'https://suhasdevmane.github.io'
baseurl: ""  # Ensure baseurl is empty for user/organization site
rss: RSS
twitter_username: suhasdevmane
github_username: suhasdevmane

# Bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# Customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: /assets/gitbook/images/favicon.ico

# Markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  docs:
    output: true
    permalink: /docs/:path/
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - docs
  - pages

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

# Load additional custom stylesheet overrides
extra_css:
  - assets/gitbook/code-dark.css
